---
- name: This is a hello-world example
  hosts: awx-1
  tasks:
    - name: Create a file called '/tmp/awx-1' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/testfile.txt
